config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  namespace :scheduler do
  	resources :users 
  	resources :schedules, :except => [:show] do
  		member do
  			get :'schedule_change_requests'
        get :approve_request
        get :reject_request
  		end
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  resourcify
  rolify
  has_one :schedule
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/scheduler/schedules_controller.rb
class Scheduler::SchedulesController < ApplicationController
  #before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  
  def index
    
    @user_id = params[:user_id]
  
    if current_user.roles.first.name == 'developer'
      @schedules = Schedule.where(user_id: current_user.id).first
    else
      @schedules = Schedule.where(user_id: params[:user_id]).first
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    
    @user_id = params[:user_id]
    @schedule = Schedule.new

  end

  # GET /schedules/1/edit
  def edit
    @date = params[:date]
    @user_id = params[:user_id]
    @schedule = Schedule.find(params[:id])

  end

  # POST /schedules
  # POST /schedules.json
  def create
    
    params[:days] = params[:days].to_json
    params[:schedule][:days] = params[:days]
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        @user = User.find(@schedule.user_id)
        ScheduleMailer.create_schedule(@schedule, @user).deliver_now
        format.html { redirect_to scheduler_schedules_path(user_id: @user.id), notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def schedule_change_requests
    @array = []
    @schedule = Schedule.find(params[:id])
    schedule_days = Schedule.find(params[:id]).days
    schedule_days = JSON.parse schedule_days
    schedule_days.each do |n|
      if n[1]["changerequest"].present? and n[1]["changerequest"] == "true"
        @array << n
      end
    end
  end


  def approve_request
  
    @schedule = Schedule.find(params[:id])
    days = JSON.parse @schedule.days
    schedule_change_date = params[:date][0]
    puts schedule_change_date
    days[schedule_change_date]["changerequest"] = "approved"
    days = days.to_json
    @schedule.days = days
    @schedule.save!
     ScheduleMailer.schedule_request_accepted(@schedule.user).deliver_now
    redirect_to scheduler_schedules_path(user_id: @schedule.user.id)

  end

  def reject_request
    @schedule = Schedule.find(params[:id])
    days = JSON.parse @schedule.days
    schedule_change_date = params[:date][0]
    days[schedule_change_date]["changerequest"] = "rejected"
    days = days.to_json
    @schedule.days = days
    @schedule.save!
     ScheduleMailer.schedule_request_rejected(@schedule.user).deliver_now
    redirect_to scheduler_schedules_path(user_id: @schedule.user.id)

  end



  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update

    key = ''
    days_temp = params[:days]
    days_temp.each do |k|
      key = k
    end
    days_db = JSON.parse @schedule.days
    
    if days_db[key].present?
        days_db[key]["changerequest"] = "true"
        days_db = days_db.to_json
        @schedule.days = days_db
        @schedule.save!
        
    else

      update_days = params[:days].to_json

      schedule_days_length = @schedule.days.length
      @schedule.days = @schedule.days[0..schedule_days_length-2]
      update_days_length = update_days.length
      update_days = update_days[1..update_days_length]
      @schedule.days << "," << update_days
    end

    respond_to do |format|
      if @schedule.update(schedule_params)
        admin = User.with_role :admin
        ScheduleMailer.schedule_change_request(admin,update_days, @schedule.user).deliver_now
        format.html { redirect_to scheduler_schedules_path(user_id: @schedule.user.id), notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to scheduler_schedules_path(user_id: @user.id), notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:user_id,:days, :repeat_to)
    end
end

app/controllers/scheduler/users_controller.rb
class Scheduler::UsersController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    
    
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    
    @user.password = SecureRandom.hex

    respond_to do |format|
      if @user.save
        @user.add_role :developer
        @user.send_reset_password_instructions
        format.html { redirect_to scheduler_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to scheduler_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to scheduler_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:email,:password,:gender)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/scheduler/users/_form.html.erb
<%= form_for [:scheduler, @user]  do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :name %>
    </div>
    <div class="col-md-4 form-group">
      <%= form.text_field :name, class: 'form-control'  %>
    </div>
    <div class="col-md-2">
      <%= form.label :gender %>
    </div>
    <div class="col-md-4 form-group">
      <%= form.text_field :gender, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= form.label :email %>
    </div>
    <div class="col-md-4 form-group">
      <%= form.text_field :email, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/scheduler/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', scheduler_user_path(@user) %> |
<%= link_to 'Back', scheduler_users_path %>

app/views/scheduler/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>
  <div class="row">
    <div class="col-md-4">
      <%= link_to 'New User', new_scheduler_user_path, class: 'btn btn-success' %>
    </div>
    <div class="col-md-4">
      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger') %> 
    </div>
  </div>




  <table class="table">
    <thead>
      <tr>
        <th> Name </th>
        <th> Gender </th>
        <th> Email </th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.gender %></td>
          <td><%= user.email %></td>
          <% if user.roles.first.name != "admin" %>
            <td><%= link_to 'View Schedules', scheduler_schedules_path(user_id: user.id) %>
          <% end %>
          <!--td><%#= link_to 'Show', scheduler_user_path(user) %></td-->
          <!--td><%#= link_to 'Edit', edit_scheduler_user_path(user) %></td-->
          <!--td><%#= link_to 'Destroy', scheduler_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td-->
        </tr>
      <% end %>
    </tbody>



  </table>

  

  <!-- <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%# @users.each do |user| %>
        <tr>
          <td><%#= user.name %></td>
          <td><%#= user.gender %></td>
          <td><%#= user.email %></td>
          <td><%#= link_to 'View Schedules', scheduler_schedules_path(user_id: user.id) %>
          <td><%#= link_to 'Show', scheduler_user_path(user) %></td>
          <td><%#= link_to 'Edit', edit_scheduler_user_path(user) %></td>
          <td><%#= link_to 'Destroy', scheduler_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%# end %>
    </tbody>
  </table>
 -->
  <br>

  
</div>

app/views/scheduler/users/new.html.erb
<div class="container">
	<h1>New User</h1>

	<%= render 'form' %>

	<%#= link_to 'Back', scheduler_users_path %>
</div>

app/views/scheduler/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= @user.name %>
<%= @user.email %>
<%= link_to 'Edit', edit_scheduler_user_path(@user) %> |
<%= link_to 'Back', scheduler_users_path %>