config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  namespace :scheduler do
  	resources :users 
  	resources :schedules, :except => [:show] do
  		member do
  			get :'schedule_change_requests'
        get :approve_request
        get :reject_request
  		end
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	belongs_to :user
	serialize :days, JSON
	validates :user_id, presence: true
end

app/controllers/scheduler/schedules_controller.rb
class Scheduler::SchedulesController < ApplicationController
  #before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  
  def index
    
    @user_id = params[:user_id]
  
    if current_user.roles.first.name == 'developer'
      @schedules = Schedule.where(user_id: current_user.id).first
    else
      @schedules = Schedule.where(user_id: params[:user_id]).first
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    
    @user_id = params[:user_id]
    @schedule = Schedule.new

  end

  # GET /schedules/1/edit
  def edit
    @date = params[:date]
    @user_id = params[:user_id]
    @schedule = Schedule.find(params[:id])

  end

  # POST /schedules
  # POST /schedules.json
  def create
    
    params[:days] = params[:days].to_json
    params[:schedule][:days] = params[:days]
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        @user = User.find(@schedule.user_id)
        ScheduleMailer.create_schedule(@schedule, @user).deliver_now
        format.html { redirect_to scheduler_schedules_path(user_id: @user.id), notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def schedule_change_requests
    @array = []
    @schedule = Schedule.find(params[:id])
    schedule_days = Schedule.find(params[:id]).days
    schedule_days = JSON.parse schedule_days
    schedule_days.each do |n|
      if n[1]["changerequest"].present? and n[1]["changerequest"] == "true"
        @array << n
      end
    end
  end


  def approve_request
  
    @schedule = Schedule.find(params[:id])
    days = JSON.parse @schedule.days
    schedule_change_date = params[:date][0]
    puts schedule_change_date
    days[schedule_change_date]["changerequest"] = "approved"
    days = days.to_json
    @schedule.days = days
    @schedule.save!
     ScheduleMailer.schedule_request_accepted(@schedule.user).deliver_now
    redirect_to scheduler_schedules_path(user_id: @schedule.user.id)

  end

  def reject_request
    @schedule = Schedule.find(params[:id])
    days = JSON.parse @schedule.days
    schedule_change_date = params[:date][0]
    days[schedule_change_date]["changerequest"] = "rejected"
    days = days.to_json
    @schedule.days = days
    @schedule.save!
     ScheduleMailer.schedule_request_rejected(@schedule.user).deliver_now
    redirect_to scheduler_schedules_path(user_id: @schedule.user.id)

  end



  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update

    key = ''
    days_temp = params[:days]
    days_temp.each do |k|
      key = k
    end
    days_db = JSON.parse @schedule.days
    
    if days_db[key].present?
        days_db[key]["changerequest"] = "true"
        days_db = days_db.to_json
        @schedule.days = days_db
        @schedule.save!
        
    else

      update_days = params[:days].to_json

      schedule_days_length = @schedule.days.length
      @schedule.days = @schedule.days[0..schedule_days_length-2]
      update_days_length = update_days.length
      update_days = update_days[1..update_days_length]
      @schedule.days << "," << update_days
    end

    respond_to do |format|
      if @schedule.update(schedule_params)
        admin = User.with_role :admin
        ScheduleMailer.schedule_change_request(admin,update_days, @schedule.user).deliver_now
        format.html { redirect_to scheduler_schedules_path(user_id: @schedule.user.id), notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to scheduler_schedules_path(user_id: @user.id), notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:user_id,:days, :repeat_to)
    end
end

app/controllers/scheduler/users_controller.rb
class Scheduler::UsersController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    
    
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    
    @user.password = SecureRandom.hex

    respond_to do |format|
      if @user.save
        @user.add_role :developer
        @user.send_reset_password_instructions
        format.html { redirect_to scheduler_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to scheduler_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to scheduler_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:email,:password,:gender)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/scheduler/schedules/_edit_form.html.erb
<%= form_for [:scheduler, @schedule] do |form| %>
	<% h = 'days['+ @date + ']' %>
	<div class="row">
		<div class="col-md-2">
			<%= form.label "Start Time" %>
		</div>
		<div class="col-md-4 form-group">
			<%= form.text_field :days, name: h+'[start_time]', value: '', class: 'timepicker form-control' %>
		</div>

		<div class="col-md-2">
			<%= form.label "End Time" %>
		</div>
		<div class="col-md-4 form-group">
			<%= form.text_field :days, name: h+'[end_time]', value: '', class: 'timepicker form-control' %>
		</div>
	</div>

	<div class="row">
		<%= form.hidden_field :days, name: h+'[changerequest]', value: 'true' %>
		<%= form.hidden_field :user_id, value: user_id %>
		<div class="col-md-4 col-md-offset-2">
			<div class="actions">
				<%= form.submit %>
			</div>
		</div>
	</div>

<% end %>

app/views/scheduler/schedules/_form.html.erb
<div class="container">
<%= form_for [:scheduler, @schedule] do |form| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%#= text_field_tag 'days[monday][start_time]', class: 'timepicker' %>
    <%#= text_field_tag 'days[monday][end_time]', class: 'timepicker' %>
    <%#= text_field_tag 'days[tuesday][start_time]', class: 'timepicker' %>
    <%#= text_field_tag 'days[tuesday][end_time]', class: 'timepicker' %>

    
   <!--div class="form-inline"-->
   <div class="row">
    <div class="col-md-2">
      <%= form.label "Monday Start Time" %>
    </div>
    <div class="col-md-4 form-group">
    <%= form.text_field :days, name: "days[monday][start_time]",  class:'timepicker form-control' %>
    </div>
    <!--div class="form-group"-->
    <div class="col-md-2">
      <%= form.label "Monday End Time" %>
    </div>
    <div class="col-md-4 form-group">
    <%= form.text_field :days, name: "days[monday][end_time]", class:'timepicker form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= form.label "Tuesday Start Time" %>
    </div>
    <div class="col-md-4 form-group">
      <%= form.text_field :days, name: "days[tuesday][start_time]", class:'timepicker form-control' %>
    </div>
    <div class="col-md-2">
      <%= form.label "Tuesday End Time" %>
    </div>
    <div class="form-group col-md-4">
      <%= form.text_field :days, name: "days[tuesday][end_time]", class:'timepicker form-control' %>
    </div>
  </div>
    
    <div class="row">
      <div class="col-md-2">
        <%= form.label "Wednesday Start Time" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.text_field :days, name: "days[wednesday][start_time]", class:'timepicker form-control' %>
      </div>

      <div class="col-md-2">
        <%= form.label "Wednesday End Time" %>
      </div>

      <div class="form-group col-md-4">
        <%= form.text_field :days, name: "days[wednesday][end_time]", class:'timepicker form-control' %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-2">
        <%= form.label "Thursday Start Time" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.text_field :days, name: "days[thursday][start_time]", class:'timepicker form-control' %>
      </div>

      <div class="col-md-2">
        <%= form.label "Thursday End Time" %>
      </div>

      <div class="form-group col-md-4">
      <%= form.text_field :days, name: "days[thursday][end_time]", class:'timepicker form-control' %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-2">
        <%= form.label "friday Start Time" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.text_field :days, name: "days[friday][start_time]", class:'timepicker form-control' %>
      </div>
      <div class="col-md-2">
        <%= form.label "Friday End Time" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.text_field :days, name: "days[friday][end_time]", class:'timepicker form-control' %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label "Saturday Start Time" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.text_field :days, name: "days[saturday][start_time]", class:'timepicker form-control'%>
      </div>

      <div class="col-md-2">
        <%= form.label "Saturday End Time" %>
      </div>
    
      <div class="form-group col-md-4">
      <%= form.text_field :days, name: "days[saturday][end_time]", class:'timepicker form-control' %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label "Sunday Start Time" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.text_field :days, name: "days[sunday][start_time]", class:'timepicker form-control' %>
      </div>
    
      <div class="col-md-2">
        <%= form.label "Sunday End Time" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.text_field :days, name: "days[sunday][end_time]", class:'timepicker form-control' %>
      </div>
    </div>
    
    <%= form.hidden_field :user_id, value: user_id %>
    <div class="row">
      <div class="col-md-2">
        <%= form.label :repeat_to %>
      </div>
      <div class="form-group col-md-4">
        <%= form.text_field :repeat_to, class:'date-picker form-control' %>
      </div>
      <div class="actions btn btn-md">
      <%= form.submit %>
      </div>
    </div>
  </div>

  
<% end %>
<!--/div-->


<!-- <script type="text/javascript">
$(function(){
  $('.timepicker').datetimepicker({ 
    format: 'LT'
  });
  $('.date-picker').datetimepicker({
    format: 'YYYY-MM-DD'
  })
});

  


</script> -->

app/views/scheduler/schedules/edit.html.erb
<div class="container">
	<h1>Editing Schedule</h1>
	<div class="row">
		<div class="col-md-2">
			<h5> Date </h5>
		</div>
		<div class="col-md-2">
			<h5> <%= @date %> </h5>
		</div>
	</div>

	<%= render 'edit_form', schedule: @schedule, user_id: @user_id, date: @date %>
</div>

<%#= link_to 'Show', @schedule %> |
<%#= link_to 'Back', schedules_path %>

app/views/scheduler/schedules/index.html.erb
<div class="container" >
  <p id="notice"><%= notice %></p>

    <div class="row">
      <div class="col-md-3">
        <h1>Schedules</h1>
      </div>
      <% if current_user.roles.first.name == 'admin' %>
        <% if @schedules.present?  %>
          <div class="col-md-3">
            <%= link_to 'View Schedule Requests', schedule_change_requests_scheduler_schedule_path(@schedules), class: 'btn btn-primary' %>
          </div>
        <% else %>
          <div class="col-md-3">
            <%= link_to 'New Schedule', new_scheduler_schedule_path(user_id: @user_id), class: 'btn btn-primary ' %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="row">
      <div class="col-md-3">
        <h4> Date </h4>
      </div>
      <div class="col-md-3">
        <h4> Start Time </h4>
      </div>
      <div class="col-md-3">
        <h4> End Time </h4>
      </div>
      <div class="col-md-3">
        <h4> Actions </h4>
      </div>
    </div>


    <% if @schedules.present? %>
      <% if @schedules.repeat_to.present? %>
        <% if @schedules.repeat_to > Date.today %>
          <% days_string = JSON.parse @schedules.days %>
          <% monday = days_string["monday"] %>
          <% tuesday = days_string["tuesday"] %>
          <% wednesday = days_string["wednesday"] %>
          <% thursday = days_string["thursday"] %>
          <% friday = days_string["friday"] %>
          <% saturday = days_string["saturday"] %>
          <% sunday = days_string["sunday"] %>


          <% sd = Date.today %>
          <%= sd.upto(@schedules.repeat_to).each do |day| %>
              <% day1 = day.to_s %>
              <% if days_string[day1].present? and days_string[day1]["changerequest"] == "approved" %>
                  <div class="row">
                    <div class="col-md-3">
                      <%= day %>
                    </div>
                    <div class="col-md-3">
                      <%= days_string[day1]["start_time"] %>
                    </div>
                    <div class="col-md-3">
                      <%= days_string[day1]["end_time"] %>
                    </div>


                    <% current_scheduler_datetime = day1 + " " + days_string[day1]["start_time"] %>
                    <% current_scheduler_datetime = current_scheduler_datetime.to_datetime %>
                    <% comparison_datetime = Time.now + 24.hours %>
                    <% if current_scheduler_datetime > comparison_datetime and current_user.roles.first.name != "admin" %>
                      <div class="col-md-3">
                        <%= link_to 'Schedule Change Request',  edit_scheduler_schedule_path(@schedules, user_id: @user_id, date: day) %>
                      </div>
                    <% end %> 
                  </div>

              <% else %>
                <% if day.wday == 0 and sunday["start_time"].present? and sunday["end_time"].present? %>
                  <div class="row">
                    <div class="col-md-3">
                      <%= day %>
                    </div>
                    <div class="col-md-3">
                      <%= sunday["start_time"] %>
                    </div>
                    <div class="col-md-3">
                      <%= sunday["end_time"] %>
                    </div>

                    <% if days_string[day1].present? and days_string[day1]["changerequest"] == "true" %>
                      <%= "Schedule Change Request Sent" %>
                    <% else %>
                      <% current_scheduler_datetime = day1 + " " + sunday["start_time"] %>
                      <% current_scheduler_datetime = current_scheduler_datetime.to_datetime %>
                      <% comparison_datetime = Time.now + 24.hours %>
                      <% if current_scheduler_datetime > comparison_datetime and current_user.roles.first.name != "admin" %>
                        <div class="col-md-3">
                          <%= link_to 'Schedule Change Request',  edit_scheduler_schedule_path(@schedules, user_id: @user_id, date: day) %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>


                <% elsif day.wday == 1 and monday["start_time"].present? and monday["end_time"].present? %>
                  <div class="row">
                    <div class="col-md-3">
                      <%= day %>
                    </div>
                    <div class="col-md-3">
                      <%= monday["start_time"] %>
                    </div>
                    <div class="col-md-3">
                      <%= monday["end_time"] %>
                    </div>

                    <% if days_string[day1].present? and days_string[day1]["changerequest"] == "true" %>
                      <%= "Schedule Change Request Sent" %>
                    <% else %>
                      <% current_scheduler_datetime = day1 + " " + monday["start_time"] %>
                      <% current_scheduler_datetime = current_scheduler_datetime.to_datetime %>
                      <% comparison_datetime = Time.now + 24.hours %>
                      <% if current_scheduler_datetime > comparison_datetime and current_user.roles.first.name != "admin" %>
                        <div class="col-md-3">
                          <%= link_to 'Schedule Change Request',  edit_scheduler_schedule_path(@schedules, user_id: @user_id, date: day) %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>

                <% elsif day.wday == 2 and tuesday["start_time"].present? and tuesday["end_time"].present? %>
                  <div class="row">
                    <div class="col-md-3">
                      <%= day %>
                    </div>
                    <div class="col-md-3">
                      <%= tuesday["start_time"] %>
                    </div>
                    <div class="col-md-3">
                      <%= tuesday["end_time"] %>
                    </div>

                    <% if days_string[day1].present? and days_string[day1]["changerequest"] == "true" %>
                      <%= "Schedule Change Request Sent" %>
                    <% else %>
                      <% current_scheduler_datetime = day1 + " " + tuesday["start_time"] %>
                      <% current_scheduler_datetime = current_scheduler_datetime.to_datetime %>
                      <% comparison_datetime = Time.now + 24.hours %>
                      <% if current_scheduler_datetime > comparison_datetime and current_user.roles.first.name != "admin" %>
                        <div class="col-md-3">
                          <%= link_to 'Schedule Change Request',  edit_scheduler_schedule_path(@schedules, user_id: @user_id, date: day) %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>

                <% elsif day.wday == 3 and wednesday["start_time"].present? and wednesday["end_time"].present? %>
                  <div class="row">
                    <div class="col-md-3">
                      <%= day %>
                    </div>
                    <div class="col-md-3">
                      <%= wednesday["start_time"] %>
                    </div>
                    <div class="col-md-3">
                      <%= wednesday["end_time"] %>
                    </div>
                    <% if days_string[day1].present? and days_string[day1]["changerequest"] == "true" %>
                      <%= "Schedule Change Request Sent" %>
                    <% else %>
                      <% current_scheduler_datetime = day1 + " " + wednesday["start_time"] %>
                      <% current_scheduler_datetime = current_scheduler_datetime.to_datetime %>
                      <% comparison_datetime = Time.now + 24.hours %>
                      <% if current_scheduler_datetime > comparison_datetime and current_user.roles.first.name != "admin" %>
                        <div class="col-md-3">
                          <%= link_to 'Schedule Change Request',  edit_scheduler_schedule_path(@schedules, user_id: @user_id, date: day) %>
                        </div>
                      <% end %>                 
                    <% end %>
                  </div>


                <% elsif day.wday == 4 and thursday["start_time"].present? and thursday["end_time"].present? %>
                  <div class="row">
                    <div class="col-md-3">
                      <%= day %>
                    </div>
                    <div class="col-md-3">
                      <%= thursday["start_time"] %>
                    </div>
                    <div class="col-md-3">
                      <%= thursday["end_time"] %>
                    </div>

                    <% if days_string[day1].present? and days_string[day1]["changerequest"] == "true" %>
                      <%= "Schedule Change Request Sent" %>
                    <% else %>
                      <% current_scheduler_datetime = day1 + " " + thursday["start_time"] %>
                      <% current_scheduler_datetime = current_scheduler_datetime.to_datetime %>
                      <% comparison_datetime = Time.now + 24.hours %>
                      <% if current_scheduler_datetime > comparison_datetime and current_user.roles.first.name != "admin" %>
                        <div class="col-md-3">
                          <%= link_to 'Schedule Change Request',  edit_scheduler_schedule_path(@schedules, user_id: @user_id, date: day) %>
                        </div>
                      <% end %>                 
                    <% end %>
                  </div> 

                <% elsif day.wday == 5 and friday["start_time"].present? and friday["end_time"].present? %>
                  <div class="row">
                    <div class="col-md-3">
                      <%= day %>
                    </div>
                    <div class="col-md-3">
                      <%= friday["start_time"] %>
                    </div>
                    <div class="col-md-3">
                      <%= friday["end_time"] %>
                    </div>

                    <% if days_string[day1].present? and days_string[day1]["changerequest"] == "true" %>
                      <%= "Schedule Change Request Sent" %>
                    <% else %>
                      <% current_scheduler_datetime = day1 + " " + friday["start_time"] %>
                      <% current_scheduler_datetime = current_scheduler_datetime.to_datetime %>
                      <% comparison_datetime = Time.now + 24.hours %>
                      <% if current_scheduler_datetime > comparison_datetime and current_user.roles.first.name != "admin" %>
                        <div class="col-md-3">
                          <%= link_to 'Schedule Change Request',  edit_scheduler_schedule_path(@schedules, user_id: @user_id, date: day) %>
                        </div>
                      <% end %>                 
                    <% end %>
                  </div> 

                <% elsif day.wday == 6 and saturday["start_time"].present? and saturday["end_time"].present? %>
                  <div class="row">
                    <div class="col-md-3">
                      <%= day %>
                    </div>
                    <div class="col-md-3">
                      <%= saturday["start_time"] %>
                    </div>
                    <div class="col-md-3">
                      <%= saturday["end_time"] %>
                    </div>

                    <% if days_string[day1].present? and days_string[day1]["changerequest"] == "true" %>
                      <%= "Schedule Change Request Sent" %>
                    <% else %>
                      <% current_scheduler_datetime = day1 + " " + saturday["start_time"] %>
                      <% current_scheduler_datetime = current_scheduler_datetime.to_datetime %>
                      <% comparison_datetime = Time.now + 24.hours %>
                      <% if current_scheduler_datetime > comparison_datetime and current_user.roles.first.name != "admin" %>
                        <div class="col-md-3">
                          <%= link_to 'Schedule Change Request',  edit_scheduler_schedule_path(@schedules, user_id: @user_id, date: day) %>
                        </div>
                      <% end %>                 
                    <% end %>
                  </div>
                <% end %>
              <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>



  <!--table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%# @schedules.each do |schedule| %>
        <tr>

          <td><%#= link_to 'Show', scheduler_schedule_path %></td>
          <td><%#= link_to 'Edit', edit_scheduler_schedule_path(schedule) %></td>
          <td><%#= link_to 'Destroy', scheduler_schedule_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <#% end %>
    </tbody>
  </table-->

  <br>

  
</div>

app/views/scheduler/schedules/new.html.erb
<div class="container">
	<h1>New Schedule</h1>

	<%= render 'form', schedule: @schedule, user_id: @user_id %>
</div>

<%#= link_to 'Back', scheduler_schedules_path %>

app/views/scheduler/schedules/schedule_change_requests.html.erb
<% @array.each do |schedule| %>
	
	<div class="container">
		<h2> Schedule Requests Approval/Rejection </h2>

		<div class="row">
			<div class="col-md-1">
				Date 
			</div>
			<div class="col-md-2">
				<%= schedule[0] %>
			</div>
			<div class="col-md-1">
				Start Time
			</div>
			<div class="col-md-1">
				<%= schedule[1]["start_time"] %>
			</div>
			<div class="col-md-1">
				End Time
			</div>
			<div class="col-md-1">
				<%= schedule[1]["end_time"] %>
			</div>
			<div class="col-md-1">
				<%= link_to 'Approved' , approve_request_scheduler_schedule_path(@schedule, date: schedule) %>
			</div>
			<div class="col-md-1">
				<%= link_to 'Reject', 	 reject_request_scheduler_schedule_path(@schedule, date: schedule) %>
			</div>
		</div>
	</div>
<% end %>